version: "3"
services:
  server:
    build: ./server
    command: npm start
    ports:
      - "5001:5000"
    networks:
      - hyzen
  client:
    build: ./client
    ports:
      - "3000:80"
      - "3001:9090"
    networks:
      - hyzen
  cache:
    image: memcached
    ports:
      - "11211:11211"
    command: -m 64
    networks:
      - hyzen

networks:
  hyzen:
    driver: bridge
